language: ruby
sudo: false
rvm:
  - 2.6
  - 2.7
  - 3.0
before_install:
  - gem update --system
gemfile:
  - gemfiles/rails_6.0.gemfile
  - gemfiles/rails_6.1.gemfile
  - gemfiles/rails_master.gemfile
jobs:
  exclude:
    - rvm: 2.6
      gemfile: gemfiles/rails_master.gemfile
